[profile.default]
src = "src"
out = "out"
libs = ["../lib"]

[profile.default.remappings]
remappings = [
"forge-std/=../lib/forge-std/src/",
"openzeppelin/=../lib/openzeppelin-contracts/contracts/",
"axelar/=../lib/axelar-gmp-sdk-solidity/contracts/",
"chainlink/=../lib/chainlink/contracts/src/v0.8/",
"chainlink-ccip/=../lib/ccip/contracts/src/v0.8/ccip/",
"hyperlane/=../lib/hyperlane-monorepo/solidity/contracts/"
]
